@hostname = localhost
@port = 80
@host = {{hostname}}:{{port}}

# get all trainees
GET http://{{host}}/api/coin/update HTTP/1.1

###

# get all trainees
GET http://{{host}}/api/portfolio HTTP/1.1

###

